# ==========================================
# Etapa 1: Construcción (Builder)
# ==========================================
FROM node:18-alpine as build

WORKDIR /app

# Copiamos package.json primero para usar la caché de Docker (Builds más rápidos)
COPY package.json package-lock.json ./
# Instalación limpia de dependencias
RUN npm ci --silent

# Copiamos el resto del código
COPY . .

# Argumento para inyectar la URL de la API al momento de construir
# Por defecto usará localhost, pero se puede sobrescribir
ARG VITE_API_URL=http://localhost:8000
ENV VITE_API_URL=$VITE_API_URL

# Construimos la app (genera la carpeta /dist)
RUN npm run build

# ==========================================
# Etapa 2: Servidor de Producción (Nginx)
# ==========================================
FROM nginx:alpine

# Copiamos solo los archivos compilados de la etapa anterior
COPY --from=build /app/dist /usr/share/nginx/html

# Copiamos nuestra configuración de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]